hash-format = "sha256"

[[files]]
file = "config/incontrol/spawn.json"
hash = "0453f86ab61f20ac2f1ed5f0aa295931a67eecd5911e79a08c18c6deb483c684"

[[files]]
file = "config/paxi/resourcepacks/cobblemon-classic-grass-pack.pw.toml"
hash = "754accb4ac44c21fa37c0216c6210b8e13e6c98248b3808d44be01c097c196c7"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/cobblemon-interface-modded.pw.toml"
hash = "f812bf391fc0a1577007d566a1c87c4aa65286f56880b05552f186d28ebced52"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/cobblemon-interface.pw.toml"
hash = "e06201469ddceef04df19dd7b992adceae3b6bf95ee602fe1272450050d749d0"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/e19_cobblemon_minimap_icons.pw.toml"
hash = "7925ee20a72c3400d470b982fcd788808d25e5446b4d456afad03da484456874"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/puffradio.pw.toml"
hash = "b67df59b9ed2d7c5b6fd827848b7000a6a7297aeb78bc20242666a1989c24333"
metafile = true

[[files]]
file = "configureddefaults/config/xaerominimap.txt"
hash = "30c2864ceaf8e91638d16d637faa02e9ee424ea09756899d8710477e603f9d7f"

[[files]]
file = "configureddefaults/config/xaerominimap_entities.json"
hash = "c98b3eceaa6603d1ab93d210dce961205e52d8ef8d9722e4e866b4d4e0987348"

[[files]]
file = "configureddefaults/config/xaeroplus.txt"
hash = "7ca1b6438c4474fd8471deb0f5b457c020a73e1e0246b2a0ffece62ffb755a9f"

[[files]]
file = "configureddefaults/config/xaeroworldmap.txt"
hash = "75a307c587e57be2dc9c5ec5483efa133e7d96a0bf8a82af3e1010f9595c6ae3"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "92b785cf953bb09b2629dde4d160c47cfabafad5c725976d69dcc524dc1add58"
metafile = true

[[files]]
file = "mods/cobblemon-ride-on.pw.toml"
hash = "63d78f5b82e034c0ba8dde7baeaa941466996125bbd67f996aab2f3e279afa4b"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "e3cb1eb238192071af93f764e3ff2c493f4f437802bb56273f664bafdea13f1d"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "edccf044df3d6519c3f8cb35e1044687d1b5bdc676fdce919d0844a4d2515685"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "06defd5b677cbcff268cfd5b3be61f5f68f8d27ae4bad06b291b8569e5f0eea0"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "8e5f6550359e71ecbea95705ec61fb03313550e6f481cabf48043929909aabae"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "975f1280c712d2e86dd4ecddf89c516afbf3f1fb684499d3e5c71fc666c4888c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/immersive-snow.pw.toml"
hash = "c8f17b808582f80a8afe90f44844ae83965afe6372c572ac5a27d595ad8c59b0"
metafile = true

[[files]]
file = "mods/in-control.pw.toml"
hash = "4903625825e4f512ac31b9a368d351a8acdfac999b769b7b7e47404927dc0e6a"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "3f1f9125896bff9902e3d4f9587723bb550060e7979ca787f06a44d1acb09ae8"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "91696791780719730cb8826de0c53d8513a7c2b320f7d641dbeb6ca974e5cec3"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "215d597764d5c5db89e700fc3495b72dc0a7f09c975de19dc8c580bde3469a5e"
metafile = true

[[files]]
file = "mods/seasonhud.pw.toml"
hash = "d009a881fb3d7bf5d7a863896ce29b2637ea224c16ad20c046702f7642b37a47"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "73b1e4f6608fcd396acc3e4e7aa753d314c8810ef4caf831ed93d9932d93f896"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "03636eaa65730e65639d1e5c560045017117876837c0a8c48fe0798ca1f7854e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "secrets.sh.example"
hash = "4fb95a91360905eaa506c6c885174a7b6a4723e2ef344c24e374608761c347e9"
