hash-format = "sha256"

[[files]]
file = "config/incontrol/spawn.json"
hash = "0453f86ab61f20ac2f1ed5f0aa295931a67eecd5911e79a08c18c6deb483c684"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "92b785cf953bb09b2629dde4d160c47cfabafad5c725976d69dcc524dc1add58"
metafile = true

[[files]]
file = "mods/cobblemon-ride-on.pw.toml"
hash = "63d78f5b82e034c0ba8dde7baeaa941466996125bbd67f996aab2f3e279afa4b"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "e3cb1eb238192071af93f764e3ff2c493f4f437802bb56273f664bafdea13f1d"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "06defd5b677cbcff268cfd5b3be61f5f68f8d27ae4bad06b291b8569e5f0eea0"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "8e5f6550359e71ecbea95705ec61fb03313550e6f481cabf48043929909aabae"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "975f1280c712d2e86dd4ecddf89c516afbf3f1fb684499d3e5c71fc666c4888c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/in-control.pw.toml"
hash = "4903625825e4f512ac31b9a368d351a8acdfac999b769b7b7e47404927dc0e6a"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a9593968393bae08257ba9aae887ad60fc49991f676b637006b2bcd89907f09a"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "91696791780719730cb8826de0c53d8513a7c2b320f7d641dbeb6ca974e5cec3"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "secrets.sh.example"
hash = "4fb95a91360905eaa506c6c885174a7b6a4723e2ef344c24e374608761c347e9"
