name = "torimon"
author = "kinggeert, jordy_vogeltjes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54126de1440c65e994cdd37d051fa1aa535a254f94a7ec620602d918b1e5603f"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
