name = "Torimon"
author = "geertbruls, jordyslagter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52de716405867bd32f7439341b84f3c498ef69fc258d71d9d6fc82e3a6738c65"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
acceptable-game-versions = ["1.21.1"]
