name = "Torimon"
author = "geertbruls, jordyslagter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae250a87ca4a24731b635feaf41b5b6d17d4005871785b3ae4b3de971ccd6c95"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
acceptable-game-versions = ["1.21.1"]
